info:
  description: ''
  title: ''
  version: ''
openapi: 3.0.0
paths:
  /grants/:
    get:
      description: API endpoint that allows grants to be viewed or edited.
      operationId: grants_list
      parameters:
      - in: query
        name: page
        schema:
          description: A page number within the paginated result set.
          title: Page
          type: integer
      - in: query
        name: assigned_data_centre
        schema:
          description: ''
          title: ''
          type: string
      - in: query
        name: grant_ref
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - grants
    post:
      description: API endpoint that allows grants to be viewed or edited.
      operationId: grants_create
      tags:
      - grants
  /grants/{id}/:
    delete:
      description: API endpoint that allows grants to be viewed or edited.
      operationId: grants_delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this grant.
          title: ID
          type: integer
      - in: query
        name: assigned_data_centre
        schema:
          description: ''
          title: ''
          type: string
      - in: query
        name: grant_ref
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - grants
    get:
      description: API endpoint that allows grants to be viewed or edited.
      operationId: grants_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this grant.
          title: ID
          type: integer
      - in: query
        name: assigned_data_centre
        schema:
          description: ''
          title: ''
          type: string
      - in: query
        name: grant_ref
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - grants
    patch:
      description: API endpoint that allows grants to be viewed or edited.
      operationId: grants_partial_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this grant.
          title: ID
          type: integer
      - in: query
        name: assigned_data_centre
        schema:
          description: ''
          title: ''
          type: string
      - in: query
        name: grant_ref
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - grants
    put:
      description: API endpoint that allows grants to be viewed or edited.
      operationId: grants_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this grant.
          title: ID
          type: integer
      - in: query
        name: assigned_data_centre
        schema:
          description: ''
          title: ''
          type: string
      - in: query
        name: grant_ref
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - grants
  /importedgrants/:
    get:
      description: API endpoint that allows grants to be viewed or edited.
      operationId: importedgrants_list
      parameters:
      - in: query
        name: page
        schema:
          description: A page number within the paginated result set.
          title: Page
          type: integer
      tags:
      - importedgrants
    post:
      description: API endpoint that allows grants to be viewed or edited.
      operationId: importedgrants_create
      tags:
      - importedgrants
  /importedgrants/{id}/:
    delete:
      description: API endpoint that allows grants to be viewed or edited.
      operationId: importedgrants_delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this imported grant.
          title: ID
          type: integer
      tags:
      - importedgrants
    get:
      description: API endpoint that allows grants to be viewed or edited.
      operationId: importedgrants_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this imported grant.
          title: ID
          type: integer
      tags:
      - importedgrants
    patch:
      description: API endpoint that allows grants to be viewed or edited.
      operationId: importedgrants_partial_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this imported grant.
          title: ID
          type: integer
      tags:
      - importedgrants
    put:
      description: API endpoint that allows grants to be viewed or edited.
      operationId: importedgrants_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this imported grant.
          title: ID
          type: integer
      tags:
      - importedgrants
  /permission/:
    get:
      description: API endpoint that allows permissions to be viewed or edited.
      operationId: permission_list
      parameters:
      - in: query
        name: page
        schema:
          description: A page number within the paginated result set.
          title: Page
          type: integer
      tags:
      - permission
    post:
      description: API endpoint that allows permissions to be viewed or edited.
      operationId: permission_create
      tags:
      - permission
  /permission/{id}/:
    delete:
      description: API endpoint that allows permissions to be viewed or edited.
      operationId: permission_delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this permission.
          title: ID
          type: integer
      tags:
      - permission
    get:
      description: API endpoint that allows permissions to be viewed or edited.
      operationId: permission_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this permission.
          title: ID
          type: integer
      tags:
      - permission
    patch:
      description: API endpoint that allows permissions to be viewed or edited.
      operationId: permission_partial_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this permission.
          title: ID
          type: integer
      tags:
      - permission
    put:
      description: API endpoint that allows permissions to be viewed or edited.
      operationId: permission_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this permission.
          title: ID
          type: integer
      tags:
      - permission
  /users/:
    get:
      description: API endpoint that allows grants to be viewed or edited.
      operationId: users_list
      parameters:
      - in: query
        name: page
        schema:
          description: A page number within the paginated result set.
          title: Page
          type: integer
      - in: query
        name: email
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - users
    post:
      description: API endpoint that allows grants to be viewed or edited.
      operationId: users_create
      tags:
      - users
  /users/{id}/:
    delete:
      description: API endpoint that allows grants to be viewed or edited.
      operationId: users_delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this user.
          title: ID
          type: integer
      - in: query
        name: email
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - users
    get:
      description: API endpoint that allows grants to be viewed or edited.
      operationId: users_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this user.
          title: ID
          type: integer
      - in: query
        name: email
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - users
    patch:
      description: API endpoint that allows grants to be viewed or edited.
      operationId: users_partial_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this user.
          title: ID
          type: integer
      - in: query
        name: email
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - users
    put:
      description: API endpoint that allows grants to be viewed or edited.
      operationId: users_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this user.
          title: ID
          type: integer
      - in: query
        name: email
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - users
servers:
- url: ''
