# Generated by Django 2.2.6 on 2019-10-07 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_ref', models.CharField(blank=True, default='', max_length=50)),
                ('title', models.CharField(default='', max_length=1024)),
                ('grant_status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=50)),
                ('amount_awarded', models.IntegerField(blank=True, null=True)),
                ('call', models.CharField(blank=True, default='', max_length=1024)),
                ('grant_type', models.CharField(blank=True, default='', max_length=1024)),
                ('scheme', models.CharField(blank=True, default='', max_length=1024)),
                ('lead_grant', models.BooleanField(blank=True, null=True)),
                ('grant_holder', models.CharField(blank=True, default='', max_length=256)),
                ('department', models.CharField(blank=True, default='', max_length=256)),
                ('research_org', models.CharField(blank=True, default='', max_length=256)),
                ('address1', models.CharField(blank=True, default='', max_length=256)),
                ('address2', models.CharField(blank=True, default='', max_length=256)),
                ('city', models.CharField(blank=True, default='', max_length=256)),
                ('post_code', models.CharField(blank=True, default='', max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('work_number', models.CharField(blank=True, max_length=256, null=True)),
                ('data_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_contact_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('routing_classification', models.CharField(blank=True, max_length=256, null=True)),
                ('secondary_classification', models.CharField(blank=True, max_length=256, null=True)),
                ('science_area', models.CharField(blank=True, max_length=256, null=True)),
                ('ncas', models.BooleanField(blank=True, null=True)),
                ('nceo', models.BooleanField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('original_proposed_start_date', models.DateField(blank=True, null=True)),
                ('original_proposed_end_date', models.DateField(blank=True, null=True)),
                ('proposed_start_date', models.DateField(blank=True, null=True)),
                ('proposed_end_date', models.DateField(blank=True, null=True)),
                ('end_date_changed', models.BooleanField(blank=True, null=True)),
                ('start_date_changed', models.BooleanField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, default='')),
                ('objectives', models.TextField(blank=True, default='')),
                ('parent_grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datamad2.ImportedGrant')),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_data_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alt_data_contact_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('assigned_data_centre', models.CharField(blank=True, max_length=256, null=True)),
                ('other_data_centre', models.CharField(blank=True, max_length=256, null=True)),
                ('hide_record', models.BooleanField(blank=True, null=True)),
                ('date_contacted_pi', models.DateField(blank=True, null=True)),
                ('will_grant_produce_data', models.BooleanField(blank=True, null=True)),
                ('datasets_delivered', models.BooleanField(blank=True, help_text='Datasets Delivered as per DMP?\tSharepoint\tYes, No or Null', null=True)),
                ('sanctions_recommended', models.BooleanField(blank=True, null=True)),
                ('case_for_support_found', models.BooleanField(blank=True, null=True)),
                ('imported_grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datamad2.ImportedGrant')),
            ],
        ),
    ]
