# Generated by Django 2.2.6 on 2020-03-04 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_ref', models.CharField(blank=True, default='', max_length=50)),
                ('alt_data_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alt_data_contact_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('assigned_data_centre', models.CharField(blank=True, choices=[('BODC', 'BODC'), ('CEDA', 'CEDA'), ('EIDC', 'EIDC'), ('NGDC', 'NGDC'), ('PDC', 'PDC'), ('ADS', 'ADS')], max_length=200, null=True)),
                ('other_data_centre', models.CharField(blank=True, choices=[('BODC', 'BODC'), ('CEDA', 'CEDA'), ('EIDC', 'EIDC'), ('NGDC', 'NGDC'), ('PDC', 'PDC'), ('ADS', 'ADS')], max_length=200, null=True)),
                ('hide_record', models.BooleanField(blank=True, null=True)),
                ('date_contacted_pi', models.DateField(blank=True, null=True)),
                ('will_grant_produce_data', models.BooleanField(blank=True, null=True)),
                ('datasets_delivered', models.BooleanField(blank=True, help_text='Datasets Delivered as per DMP?', null=True)),
                ('sanctions_recommended', models.BooleanField(blank=True, null=True)),
                ('case_for_support_found', models.BooleanField(blank=True, null=True)),
                ('claimed', models.BooleanField(blank=True, null=True)),
                ('updated_imported_grant', models.BooleanField(blank=True, editable=False, null=True, verbose_name='Grant updated')),
            ],
        ),
        migrations.CreateModel(
            name='ImportedGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1024)),
                ('grant_ref', models.CharField(blank=True, default='', max_length=50)),
                ('creation_date', models.DateTimeField(editable=False)),
                ('grant_status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=50)),
                ('amount_awarded', models.IntegerField(blank=True, null=True)),
                ('grant_type', models.CharField(blank=True, default='', max_length=1024)),
                ('scheme', models.CharField(blank=True, default='', max_length=1024)),
                ('lead_grant', models.BooleanField(blank=True, null=True)),
                ('grant_holder', models.CharField(blank=True, default='', max_length=256)),
                ('department', models.CharField(blank=True, default='', max_length=256)),
                ('research_org', models.CharField(blank=True, default='', max_length=256)),
                ('address1', models.CharField(blank=True, default='', max_length=256)),
                ('address2', models.CharField(blank=True, default='', max_length=256)),
                ('city', models.CharField(blank=True, default='', max_length=256)),
                ('post_code', models.CharField(blank=True, default='', max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('work_number', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('data_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_contact_phone', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('routing_classification', models.CharField(blank=True, choices=[('Marine', 'Marine'), ('Earth', 'Earth'), ('Atmospheric', 'Atmospheric'), ('Freshwater', 'Freshwater'), ('Terrestrial', 'Terrestrial'), ('Earth Observation', 'Earth Observation')], max_length=200, null=True)),
                ('secondary_classification', models.CharField(blank=True, max_length=256, null=True)),
                ('science_area', models.CharField(blank=True, max_length=256, null=True)),
                ('ncas', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('nceo', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('proposed_start_date', models.DateField(blank=True, null=True)),
                ('proposed_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, default='')),
                ('objectives', models.TextField(blank=True, default='')),
                ('ticket', models.BooleanField(blank=True, null=True)),
                ('grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datamad2.Grant')),
                ('parent_grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datamad2.ImportedGrant')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.EmailField(max_length=255)),
                ('data_centre', models.CharField(blank=True, choices=[('BODC', 'BODC'), ('CEDA', 'CEDA'), ('EIDC', 'EIDC'), ('NGDC', 'NGDC'), ('PDC', 'PDC'), ('ADS', 'ADS')], max_length=200, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
