# Generated by Django 2.2.6 on 2020-10-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraissuetype',
            name='alt_data_contact_email_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}}', max_length=50, verbose_name='Alt Data Contact Email Field ID'),
        ),
        migrations.AddField(
            model_name='jiraissuetype',
            name='alt_data_contact_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}}', max_length=50, verbose_name='Alt Data Contact Field ID'),
        ),
        migrations.AddField(
            model_name='jiraissuetype',
            name='amount_awarded_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}}', max_length=50, verbose_name='Amount Awarded Field ID'),
        ),
        migrations.AddField(
            model_name='jiraissuetype',
            name='child_grants_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}}', max_length=50, verbose_name='Child Grants Field ID'),
        ),
        migrations.AddField(
            model_name='jiraissuetype',
            name='email_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}}', max_length=50, verbose_name='Email Field ID'),
        ),
        migrations.AddField(
            model_name='jiraissuetype',
            name='grant_type_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}}', max_length=50, verbose_name='Grant Type Field ID'),
        ),
        migrations.AddField(
            model_name='jiraissuetype',
            name='lead_grant_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}}', max_length=50, verbose_name='Lead Grant Field ID'),
        ),
        migrations.AddField(
            model_name='jiraissuetype',
            name='other_datacentre_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}}', max_length=50, verbose_name='Other Datacentre Field ID'),
        ),
        migrations.AddField(
            model_name='jiraissuetype',
            name='parent_grant_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}}', max_length=50, verbose_name='Parent Grant Field ID'),
        ),
        migrations.AddField(
            model_name='jiraissuetype',
            name='proposed_end_date_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}}', max_length=50, verbose_name='Proposed End Date Field ID'),
        ),
        migrations.AddField(
            model_name='jiraissuetype',
            name='proposed_start_date_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}}', max_length=50, verbose_name='Proposed Start Date Field ID'),
        ),
        migrations.AddField(
            model_name='jiraissuetype',
            name='work_number_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}}', max_length=50, verbose_name='Work Number Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='end_date_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}}', max_length=100, verbose_name='Actual End Date Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='start_date_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}}', max_length=100, verbose_name='Actual Start Date Field ID'),
        ),
    ]
