# Generated by Django 2.2.6 on 2019-11-19 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0001_initial'),
        ('datamad2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dmp.Project'),
        ),
    ]
