# Generated by Django 2.2.6 on 2019-11-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importedgrant',
            name='call',
        ),
        migrations.AddField(
            model_name='grant',
            name='lead_grant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='title',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
