# Generated by Django 2.2.6 on 2020-03-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='alt_data_contact',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='importedgrant',
            name='data_contact',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
