# Generated by Django 2.2.6 on 2019-11-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='title',
        ),
    ]
