# Generated by Django 2.2.10 on 2020-04-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0002_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedgrant',
            name='creation_date',
            field=models.DateField(editable=False),
        ),
    ]
