# Generated by Django 2.2.6 on 2019-11-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0002_grant_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='title',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
