# Generated by Django 2.2.6 on 2020-03-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0002_auto_20200320_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='alt_data_contact',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
