# Generated by Django 2.2.6 on 2019-11-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0002_auto_20191127_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='lead_grant',
        ),
    ]
