# Generated by Django 2.2.6 on 2019-11-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0002_remove_grant_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='claim_status',
        ),
        migrations.AddField(
            model_name='grant',
            name='Claimed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
