# Generated by Django 2.2.6 on 2020-11-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0002_auto_20201021_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedgrant',
            name='amount_awarded',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
