# Generated by Django 2.2.6 on 2020-03-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0003_auto_20200324_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='alt_data_contact',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
