# Generated by Django 2.2.13 on 2020-11-10 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0003_auto_20201104_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraissuetype',
            name='reporter',
            field=models.ForeignKey(blank=True, help_text='User to set as the reporter for all JIRA issues. If left blank the reporter will be the user that creates the issue.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='alt_data_contact_email_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Alt Data Contact Email Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='alt_data_contact_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Alt Data Contact Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='amount_awarded_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: Float', max_length=50, verbose_name='Amount Awarded Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='child_grants_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Child Grants Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='email_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Email Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='end_date_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=100, verbose_name='Actual End Date Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='grant_ref_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=100, verbose_name='Grant Ref Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='grant_type_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Grant Type Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='lead_grant_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: Boolean', max_length=50, verbose_name='Lead Grant Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='other_datacentre_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Other Datacentre Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='parent_grant_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Parent Grant Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='pi_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=100, verbose_name='Principle Investigator Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='primary_datacentre_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=100, verbose_name='Primary Datacentre Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='proposed_end_date_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Proposed End Date Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='proposed_start_date_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Proposed Start Date Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='research_org_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=100, verbose_name='Research Org Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='start_date_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=100, verbose_name='Actual Start Date Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='work_number_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Work Number Field ID'),
        ),
    ]
