# Generated by Django 2.2.6 on 2019-11-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0003_auto_20191129_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='Claimed',
            new_name='claimed',
        ),
    ]
