# Generated by Django 2.2.13 on 2020-11-19 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0004_auto_20201110_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='grant',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
