# Generated by Django 2.2.6 on 2020-11-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0004_auto_20201110_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacentre',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Datacentre Name'),
        ),
    ]
