# Generated by Django 2.2.6 on 2020-11-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0004_auto_20201110_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
