# Generated by Django 2.2.6 on 2020-03-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0004_auto_20200325_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedgrant',
            name='data_contact',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
