# Generated by Django 2.2.6 on 2019-12-16 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0004_auto_20191129_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedgrant',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
