# Generated by Django 2.2.6 on 2019-11-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0005_remove_grant_grant_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='grant_ref',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
