# Generated by Django 2.2.6 on 2019-12-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0005_importedgrant_modified_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importedgrant',
            options={'ordering': ['-modified_date']},
        ),
        migrations.AddField(
            model_name='importedgrant',
            name='ticket',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='Ticket created'),
        ),
    ]
