# Generated by Django 2.2.6 on 2020-03-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0005_auto_20200325_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='science_area',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
