# Generated by Django 2.2.6 on 2019-11-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0006_grant_grant_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importedgrant',
            name='grant_ref',
        ),
    ]
