# Generated by Django 2.2.6 on 2019-12-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0006_auto_20191217_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedgrant',
            name='ticket',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
