# Generated by Django 2.2.10 on 2020-04-27 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0006_auto_20200427_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamad2.DataCentre'),
        ),
    ]
