# Generated by Django 2.2.6 on 2020-11-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0006_grant_date_added'),
        ('datamad2', '0006_auto_20201120_1229'),
    ]

    operations = [
    ]
