# Generated by Django 2.2.6 on 2019-11-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0007_remove_importedgrant_grant_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='grant_ref',
        ),
        migrations.AddField(
            model_name='importedgrant',
            name='grant_ref',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
