# Generated by Django 2.2.10 on 2020-04-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0007_auto_20200427_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacentre',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamad2.DataCentre', to_field='name'),
        ),
    ]
