# Generated by Django 2.2.6 on 2020-12-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0007_auto_20201120_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraissuetype',
            name='call_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Call Field ID'),
        ),
        migrations.AddField(
            model_name='jiraissuetype',
            name='scheme_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Scheme Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='amount_awarded_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Amount Awarded Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='lead_grant_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}} | Returned DataType: String', max_length=50, verbose_name='Lead Grant Field ID'),
        ),
    ]
