# Generated by Django 2.2.6 on 2020-01-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0007_auto_20191217_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importedgrant',
            options={'ordering': ['-creation_date']},
        ),
        migrations.RemoveField(
            model_name='importedgrant',
            name='modified_date',
        ),
    ]
