# Generated by Django 2.2.6 on 2020-12-10 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0008_auto_20201208_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='JIRATicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamad2.Grant')),
                ('datacentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamad2.DataCentre')),
                ('url',models.URLField()),
            ],
        ),
    ]
