# Generated by Django 2.2.6 on 2020-03-05 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0008_auto_20200109_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='datasets_delivered',
            field=models.BooleanField(blank=True, help_text='Datasets Delivered as per DMP?', null=True),
        ),
        migrations.AlterField(
            model_name='importedgrant',
            name='ncas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importedgrant',
            name='nceo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importedgrant',
            name='parent_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_grant', to='datamad2.Grant'),
        ),
    ]
