# Generated by Django 2.2.6 on 2019-10-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0008_auto_20191011_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedgrant',
            name='claim_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
