# Generated by Django 2.2.6 on 2020-12-10 11:30

from django.db import migrations


def migrate_jira_tickets(apps, schema_editor):
    """
    Moving the jira ticket field to a foreign key model and need to migrate
    existing links.
    :param apps:
    :param schema_editor:
    :return:
    """

    Grant = apps.get_model('datamad2', 'Grant')
    JIRATicket = apps.get_model('datamad2', 'JIRATicket')
    for grant in Grant.objects.filter(jira_ticket__isnull=False):
        jira_ticket = JIRATicket(grant=grant, url=grant.jira_ticket, datacentre=grant.assigned_data_centre)
        jira_ticket.save()


def reverse_migrate_jira_tickets(apps, schema_editor):
    """
    Doing this would be destructive if a grant has more than one jira ticket
    :param apps:
    :param schema_editor:
    :return:
    """

    Grant = apps.get_model('datamad2', 'Grant')
    for grant in Grant.objects.all():
        if grant.jiraticket_set.count == 1:
            grant.jira_ticket = grant.jiraticket_set.first().url
            grant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0009_jiraticket'),
    ]

    operations = [
        migrations.RunPython(migrate_jira_tickets, reverse_migrate_jira_tickets)
    ]
