# Generated by Django 2.2.6 on 2019-10-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0009_auto_20191011_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedgrant',
            name='claim_status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
