# Generated by Django 2.2.6 on 2020-12-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0010_auto_20201210_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='jira_ticket',
        ),
    ]
