# Generated by Django 2.2.10 on 2020-05-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0010_dmpdocument_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
