# Generated by Django 2.2.6 on 2019-11-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0004_auto_20191121_1100'),
        ('datamad2', '0010_remove_importedgrant_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dmp.Programme'),
        ),
    ]
