# Generated by Django 2.2.6 on 2021-03-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0011_remove_grant_jira_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproduct',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
