# Generated by Django 2.2.6 on 2019-11-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0011_grant_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='lead_grant',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
