# Generated by Django 2.2.10 on 2020-05-07 10:56

import datamad2.models.document_store
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0011_auto_20200506_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('support', 'Support'), ('dmp', 'DMP')], default='support', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(storage=datamad2.models.document_store.MediaFileSystemStorage(), upload_to=datamad2.models.document_store.file_name),
        ),
        migrations.DeleteModel(
            name='DMPDocument',
        ),
    ]
