# Generated by Django 2.2.10 on 2020-05-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0012_auto_20200507_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_type',
            new_name='type',
        ),
    ]
