# Generated by Django 2.2.6 on 2019-11-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0012_grant_lead_grant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='programme',
        ),
    ]
