# Generated by Django 2.2.10 on 2020-05-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0013_auto_20200507_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-last_modified']},
        ),
    ]
