# Generated by Django 2.2.10 on 2020-05-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0014_auto_20200514_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedgrant',
            name='call',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='importedgrant',
            name='facility',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
