# Generated by Django 2.2.10 on 2020-05-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0015_auto_20200514_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedgrant',
            name='routing_classification',
            field=models.CharField(blank=True, choices=[('Marine', 'Marine'), ('Earth', 'Earth'), ('Atmospheric', 'Atmospheric'), ('Freshwater', 'Freshwater'), ('Terrestrial', 'Terrestrial'), ('Earth Observation', 'Earth Observation'), ('Panel A', 'Panel A'), ('Panel B', 'Panel B'), ('Panel C', 'Panel C')], max_length=200, null=True),
        ),
    ]
