# Generated by Django 2.2.6 on 2019-10-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0015_auto_20191017_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
