# Generated by Django 2.2.10 on 2020-05-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0015_auto_20200514_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, help_text='If left blank the title will be the name of the file.', max_length=100),
        ),
    ]
