# Generated by Django 2.2.6 on 2019-11-07 10:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0016_auto_20191017_0725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importedgrant',
            options={'ordering': ['-creation_date']},
        ),
        migrations.RemoveField(
            model_name='grant',
            name='imported_grant',
        ),
        migrations.RemoveField(
            model_name='importedgrant',
            name='claim_status',
        ),
        migrations.AddField(
            model_name='grant',
            name='claim_status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='grant_ref',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='grant',
            name='updated_imported_grant',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='Grant updated'),
        ),
        migrations.AddField(
            model_name='importedgrant',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importedgrant',
            name='grant',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='datamad2.Grant'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='assigned_data_centre',
            field=models.CharField(blank=True, choices=[('BODC', 'BODC'), ('CEDA', 'CEDA'), ('EIDC', 'EIDC'), ('NGDC', 'NGDC'), ('PDC', 'PDC'), ('ADS', 'ADS')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='other_data_centre',
            field=models.CharField(blank=True, choices=[('BODC', 'BODC'), ('CEDA', 'CEDA'), ('EIDC', 'EIDC'), ('NGDC', 'NGDC'), ('PDC', 'PDC'), ('ADS', 'ADS')], max_length=200, null=True),
        ),
    ]
