# Generated by Django 2.2.10 on 2020-05-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0016_auto_20200515_1539'),
        ('datamad2', '0016_auto_20200519_1004'),
    ]

    operations = [
    ]
