# Generated by Django 2.2.6 on 2019-11-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0017_auto_20191107_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedgrant',
            name='amount_awarded',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='importedgrant',
            name='data_contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='importedgrant',
            name='data_contact_phone',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='importedgrant',
            name='lead_grant',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='importedgrant',
            name='ncas',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importedgrant',
            name='nceo',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='importedgrant',
            name='work_number',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
