# Generated by Django 2.2.13 on 2020-06-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0017_merge_20200521_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedgrant',
            name='overall_score',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
