# Generated by Django 2.2.6 on 2019-11-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0018_auto_20191111_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importedgrant',
            name='end_date_changed',
        ),
        migrations.RemoveField(
            model_name='importedgrant',
            name='original_proposed_end_date',
        ),
        migrations.RemoveField(
            model_name='importedgrant',
            name='original_proposed_start_date',
        ),
        migrations.RemoveField(
            model_name='importedgrant',
            name='start_date_changed',
        ),
    ]
