# Generated by Django 2.2.6 on 2020-07-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0018_auto_20200611_1234'),
        ('datamad2', '0018_importedgrant_overall_score'),
    ]

    operations = [
    ]
