# Generated by Django 2.2.6 on 2019-11-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0019_auto_20191111_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedgrant',
            name='creation_date',
            field=models.DateTimeField(editable=False),
        ),
    ]
