# Generated by Django 2.2.6 on 2020-07-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0019_merge_20200716_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedgrant',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
