# Generated by Django 2.2.6 on 2020-07-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0020_auto_20200716_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedgrant',
            name='creation_date',
            field=models.DateTimeField(editable=False),
        ),
    ]
