# Generated by Django 2.2.6 on 2019-11-18 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0021_auto_20191118_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedgrant',
            name='data_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='importedgrant',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datamad2.Grant'),
        ),
        migrations.AlterField(
            model_name='importedgrant',
            name='lead_grant',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
