# Generated by Django 2.2.6 on 2020-07-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0022_auto_20200722_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_facets',
            field=models.TextField(blank=True),
        )
    ]
