# Generated by Django 2.2.6 on 2019-11-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0023_auto_20191118_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importedgrant',
            options={'ordering': ['-creation_date']},
        ),
    ]
