# Generated by Django 2.2.6 on 2019-11-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0024_auto_20191118_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedgrant',
            name='creation_date',
            field=models.DateTimeField(default='', editable=False),
        ),
    ]
