# Generated by Django 2.2.13 on 2020-08-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0024_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='ref_time',
            field=models.CharField(blank=True, choices=[('start_date', 'Start Date'), ('end_date', 'End Date')], max_length=200, null=True),
        ),
    ]
