# Generated by Django 2.2.13 on 2020-08-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0025_auto_20200804_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='ref_time',
            field=models.CharField(blank=True, choices=[('start_date', 'Start Date'), ('end_date', 'End Date')], help_text='Start date means the sub-task will be scheduled after the start date. End date means it will be scheduled before the end date.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='schedule_time',
            field=models.CharField(blank=True, help_text='Time in weeks to schedule sub task in reference to the reference time.', max_length=200, null=True),
        ),
    ]
