# Generated by Django 2.2.13 on 2020-08-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0026_auto_20200804_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='schedule_time',
            field=models.IntegerField(blank=True, help_text='Time in weeks to schedule sub task in reference to the reference time.', null=True),
        ),
    ]
