# Generated by Django 2.2.6 on 2019-11-18 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0027_remove_importedgrant_parent_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedgrant',
            name='parent_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datamad2.ImportedGrant'),
        ),
    ]
