# Generated by Django 2.2.13 on 2020-08-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0027_auto_20200804_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='ref_time',
            field=models.CharField(blank=True, choices=[('start_date', 'Start Date'), ('end_date', 'End Date')], help_text='Start date means the sub-task will be scheduled in reference to the start date. End date means it will be scheduled in reference to the end date.', max_length=200, null=True, verbose_name='Reference time'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='schedule_time',
            field=models.IntegerField(blank=True, help_text='Time in weeks to at which to schedule sub-task in reference to the reference time. Using a negative value schedules the task before the reference time', null=True, verbose_name='Schedule at'),
        ),
    ]
