# Generated by Django 2.2.6 on 2019-11-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0028_importedgrant_parent_grant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedgrant',
            name='amount_awarded',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
