# Generated by Django 2.2.6 on 2019-11-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0030_auto_20191118_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedgrant',
            name='amount_awarded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
