# Generated by Django 2.2.6 on 2020-09-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0030_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacentre',
            name='end_date_field',
            field=models.CharField(blank=True, max_length=100, verbose_name='End Date Field ID'),
        ),
        migrations.AddField(
            model_name='datacentre',
            name='grant_ref_field',
            field=models.CharField(blank=True, max_length=100, verbose_name='Grant Ref Field ID'),
        ),
        migrations.AddField(
            model_name='datacentre',
            name='issuetype',
            field=models.IntegerField(blank=True, help_text='JIRA Data Management issue type ID', null=True),
        ),
        migrations.AddField(
            model_name='datacentre',
            name='pi_field',
            field=models.CharField(blank=True, max_length=100, verbose_name='Grant Holder Field ID'),
        ),
        migrations.AddField(
            model_name='datacentre',
            name='primary_datacentre_field',
            field=models.CharField(blank=True, max_length=100, verbose_name='Primary Datacentre Field ID'),
        ),
        migrations.AddField(
            model_name='datacentre',
            name='research_org_field',
            field=models.CharField(blank=True, max_length=100, verbose_name='Research Org Field ID'),
        ),
        migrations.AddField(
            model_name='datacentre',
            name='start_date_field',
            field=models.CharField(blank=True, max_length=100, verbose_name='Start Date Field ID'),
        ),
        migrations.AlterField(
            model_name='datacentre',
            name='jira_project',
            field=models.CharField(blank=True, max_length=100, verbose_name='Data Management JIRA Project'),
        ),
        migrations.AlterField(
            model_name='datacentre',
            name='name',
            field=models.CharField(choices=[('BODC', 'BODC'), ('CEDA', 'CEDA'), ('EIDC', 'EIDC'), ('NGDC', 'NGDC'), ('PDC', 'PDC'), ('ADS', 'ADS')], max_length=100, null=True, unique=True, verbose_name='Datacentre Name'),
        ),
    ]
