# Generated by Django 2.2.13 on 2020-09-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0031_auto_20200917_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacentre',
            name='end_date_field',
            field=models.CharField(blank=True, help_text='Format: customfield_<number>', max_length=100, verbose_name='End Date Field ID'),
        ),
        migrations.AlterField(
            model_name='datacentre',
            name='grant_ref_field',
            field=models.CharField(blank=True, help_text='Format: customfield_<number>', max_length=100, verbose_name='Grant Ref Field ID'),
        ),
        migrations.AlterField(
            model_name='datacentre',
            name='issuetype',
            field=models.IntegerField(blank=True, help_text='JIRA Data Management issue type ID. e.g. 10602', null=True),
        ),
        migrations.AlterField(
            model_name='datacentre',
            name='pi_field',
            field=models.CharField(blank=True, help_text='Format: customfield_<number>', max_length=100, verbose_name='Principle Investigator Field ID'),
        ),
        migrations.AlterField(
            model_name='datacentre',
            name='primary_datacentre_field',
            field=models.CharField(blank=True, help_text='Format: customfield_<number>', max_length=100, verbose_name='Primary Datacentre Field ID'),
        ),
        migrations.AlterField(
            model_name='datacentre',
            name='research_org_field',
            field=models.CharField(blank=True, help_text='Format: customfield_<number>', max_length=100, verbose_name='Research Org Field ID'),
        ),
        migrations.AlterField(
            model_name='datacentre',
            name='start_date_field',
            field=models.CharField(blank=True, help_text='Format: customfield_<number>', max_length=100, verbose_name='Start Date Field ID'),
        ),
    ]
