# Generated by Django 2.2.13 on 2020-09-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0032_auto_20200923_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is the user an admin?'),
        ),
    ]
