# Generated by Django 2.2.6 on 2020-09-24 15:31

import datamad2.models.data_management_plans
import datamad2.models.document_store
from django.db import migrations, models
import django.db.models.deletion
import sizefield.models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0033_auto_20200923_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PreservationPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(storage=datamad2.models.document_store.MediaFileSystemStorage, upload_to=datamad2.models.data_management_plans.file_name)),
                ('name', models.CharField(blank=True, help_text='Name will default to mach uploaded file', max_length=100)),
                ('datacentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamad2.DataCentre')),
            ],
        ),
        migrations.CreateModel(
            name='DataProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('data_volume', sizefield.models.FileSizeField(blank=True, default=0)),
                ('delivery_date', models.DateField(blank=True)),
                ('embargo_date', models.DateField(blank=True)),
                ('doi', models.BooleanField(blank=True)),
                ('sample_type', models.CharField(blank=True, max_length=50)),
                ('sample_destination', models.CharField(blank=True, max_length=100)),
                ('issues', models.TextField(blank=True)),
                ('data_location', models.CharField(blank=True, max_length=100)),
                ('responsibility', models.CharField(blank=True, max_length=50)),
                ('additional_comments', models.TextField(blank=True)),
                ('data_format', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='datamad2.DataFormat')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamad2.Grant')),
                ('preservation_plan', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='datamad2.PreservationPlan')),
            ],
        ),
    ]
