# Generated by Django 2.2.13 on 2020-09-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0033_auto_20200923_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='date_contacted_pi',
            new_name='date_contacted_PI',
        ),
    ]
