# Generated by Django 2.2.13 on 2020-09-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0033_auto_20200923_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefered_sorting',
            field=models.TextField(null=True),
        ),
    ]
