# Generated by Django 2.2.6 on 2020-10-01 13:35

import datamad2.models.data_management_plans
import datamad2.models.document_store
from django.db import migrations, models
import django.db.models.deletion
import sizefield.models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0033_auto_20200923_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=50)),
                ('datacentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamad2.DataCentre')),
            ],
        ),
        migrations.CreateModel(
            name='PreservationPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('datacentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamad2.DataCentre')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(storage=datamad2.models.document_store.MediaFileSystemStorage(), upload_to=datamad2.models.data_management_plans.file_name)),
                ('name', models.CharField(blank=True, help_text='Name will default to mach uploaded file', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short description to help other users understand what the template is used for')),
                ('type', models.CharField(choices=[('dmp', 'DMP'), ('odmp', 'ODMP'), ('cfs', 'CFS'), ('ta', 'TA'), ('jor', 'JOR'), ('proforma', 'PROFORMA')], max_length=50)),
                ('datacentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamad2.DataCentre')),
            ],
        ),
        migrations.CreateModel(
            name='DataProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data_product_type', models.CharField(choices=[('digital', 'Digital Dataset'), ('model_source', 'Model Source Code'), ('physical', 'Pysical Collections & Samples'), ('hardcopy', 'Hardcopy Records'), ('third_party', 'Third Party/Existing Datasets')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_volume', sizefield.models.FileSizeField(blank=True, default=0, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('embargo_date', models.DateField(blank=True, null=True)),
                ('doi', models.BooleanField(blank=True, null=True, verbose_name='DOI')),
                ('sample_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sample_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('issues', models.TextField(blank=True, null=True)),
                ('data_location', models.CharField(blank=True, max_length=100, null=True)),
                ('responsibility', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('data_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datamad2.DataFormat')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamad2.Grant')),
                ('preservation_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datamad2.PreservationPlan')),
            ],
        ),
    ]
