# Generated by Django 2.2.6 on 2020-09-25 08:59

import datamad2.models.data_management_plans
import datamad2.models.document_store
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0034_dataformat_dataproduct_documenttemplate_preservationplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Short description to help other users understand what the template is used for'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='template',
            field=models.FileField(storage=datamad2.models.document_store.MediaFileSystemStorage(), upload_to=datamad2.models.data_management_plans.file_name),
        ),
    ]
