# Generated by Django 2.2.13 on 2020-09-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0034_auto_20200923_1227'),
        ('datamad2', '0032_auto_20200923_1126'),
    ]

    operations = [
    ]
