# Generated by Django 2.2.13 on 2020-09-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0035_merge_20200923_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraissuetype',
            name='end_date_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}}', max_length=100, verbose_name='End Date Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='grant_ref_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}}', max_length=100, verbose_name='Grant Ref Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='issuetype',
            field=models.IntegerField(blank=True, help_text='JIRA Data Management issue type ID. e.g. 10602', null=True, verbose_name='Issue Type Id'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='pi_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}}', max_length=100, verbose_name='Principle Investigator Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='primary_datacentre_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}}', max_length=100, verbose_name='Primary Datacentre Field ID'),
        ),
        migrations.AlterField(
            model_name='jiraissuetype',
            name='research_org_field',
            field=models.CharField(blank=True, help_text='Format: customfield_{{number}}', max_length=100, verbose_name='Research Org Field ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Give admin status'),
        ),
    ]
