# Generated by Django 2.2.6 on 2020-10-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0035_auto_20200930_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_sorting',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='date_contacted_pi',
            field=models.DateField(blank=True, null=True, verbose_name='Date contacted PI'),
        ),
    ]
