# Generated by Django 2.2.6 on 2019-11-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('data_activities', models.TextField(blank=True, help_text='Short description of data generation activities. eg Data will be collected by FAAM aircraft/ground instruments. Are there intensive measurement campaigns?', null=True)),
                ('startdate', models.DateField(blank=True, help_text='Date format dd/mm/yyyy', null=True, verbose_name='Start Date')),
                ('enddate', models.DateField(blank=True, help_text='Date format dd/mm/yyyy', null=True, verbose_name='End Date')),
                ('dmp_agreed', models.DateField(blank=True, help_text='Date format dd/mm/yyyy', null=True, verbose_name='DMP Agreed')),
                ('initial_contact', models.DateField(blank=True, help_text='Date format dd/mm/yyyy', null=True, verbose_name='Initial Contact')),
                ('PI', models.CharField(blank=True, max_length=200, null=True)),
                ('PIemail', models.EmailField(blank=True, max_length=200, null=True)),
                ('PIinst', models.CharField(blank=True, max_length=200, null=True)),
                ('Contact1', models.CharField(blank=True, max_length=200, null=True)),
                ('Contact2', models.CharField(blank=True, max_length=200, null=True)),
                ('projectcost', models.IntegerField(blank=True, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('primary_dataCentre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Primary Datacentre')),
                ('other_dataCentres', models.CharField(blank=True, max_length=200, null=True, verbose_name='Other Datacentres')),
                ('status', models.CharField(blank=True, choices=[('Proposal', 'Proposal'), ('NotFunded', 'Not Funded'), ('NotStarted', 'Not Started'), ('Active', 'Active'), ('NoData', 'No Data'), ('EndedWithDataToCome', 'Ended with data to come'), ('Defaulted', 'Defaulted'), ('NoDataForUs', 'No data for us'), ('Complete', 'Complete'), ('Unresponsive', 'Unresponsive'), ('MergedProject/HandledElsewhere', 'Merged Project/Handled Elsewhere')], max_length=200, null=True)),
                ('project_status', models.CharField(blank=True, choices=[('InitialContact', 'Initial contact'), ('DMPComms', 'DMP comms'), ('Progress', 'Progress'), ('DataDelivery', 'Data delivery')], max_length=200, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('project_URL', models.URLField(blank=True, null=True)),
                ('dmp_URL', models.URLField(blank=True, null=True, verbose_name='DMP URL')),
                ('ODMP_URL', models.URLField(blank=True, help_text='Outline DMP URL autogenerated when using grant uploader, essentially a best guess. Edit as necessary.', null=True)),
                ('moles_URL', models.URLField(blank=True, null=True)),
                ('helpscout_url', models.URLField(blank=True, null=True, verbose_name='OpMan URL')),
                ('project_usergroup', models.CharField(blank=True, help_text='Group name for registration for this group', max_length=200, null=True)),
                ('reassigned', models.BooleanField(default=False)),
            ],
        ),
    ]
