# Generated by Django 2.2.6 on 2019-11-21 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamad2', '0002_grant_project'),
        ('dmp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
            ],
            options={
                'ordering': ('first_name',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('datamad2.myuser',),
        ),
        migrations.AddField(
            model_name='project',
            name='sciSupContact',
            field=models.ForeignKey(blank=True, help_text='CEDA person contact for this Project', null=True, on_delete=django.db.models.deletion.PROTECT, to='dmp.Person'),
        ),
    ]
