# Generated by Django 2.2.6 on 2019-11-22 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sizefield.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dmp', '0004_auto_20191121_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, null=True)),
                ('datavol', sizefield.models.FileSizeField(default=0)),
                ('contact1', models.CharField(blank=True, max_length=200, null=True)),
                ('contact2', models.CharField(blank=True, max_length=200, null=True)),
                ('deliverydate', models.DateField(blank=True, null=True)),
                ('preservation_plan', models.CharField(blank=True, choices=[('Reference', 'Reference data with principal use to provide evidence for publication'), ('Structured', 'Structured data with set format and metadata conventions'), ('Interoperable', 'Interoperable data with formats and metadata conventions for specific community tools'), ('InProject', 'Data management within the project only. No archive involvement'), ('OtherRepositories', 'Other Non-NERC repositories'), ('BODC', 'British Oceanographic Data Centre'), ('EIDC', 'Environmental Information Data Centre '), ('PDC', 'Polar Data Centre'), ('NGDC', 'National Geoscience Data Centre'), ('OtherDMP', 'This data is planned within another project DMP'), ('KeepIndefinitely', 'Keep Indefinitely'), ('KeepAsIs', 'Keep as is - Even if obsolete'), ('Dispose5years ', 'Review for disposal 5 years after project completes'), ('ManageInProject', "Don't Archive - manage the data within the project"), ('Subset', 'Plan to keep a subset of the data indefinitely'), ('TBD', 'TBD')], max_length=200, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('review_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('WithProjectTeam', 'With Project Team'), ('Ingesting', 'Ingesting'), ('Archived', 'Archived and complete'), ('Defaulted', 'Defaulted - not archived due to project not supplying data'), ('NotArchived', 'Not going to archive - planned')], max_length=200, null=True)),
                ('data_URL', models.URLField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, help_text='Project producing this data', null=True, on_delete=django.db.models.deletion.PROTECT, to='dmp.Project')),
                ('sciSupContact', models.ForeignKey(blank=True, help_text='CEDA person contact for this data', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
